/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.omg.CORBA.OBJECT_NOT_EXIST;

/**
 *
 * @author Aaron
 */
public class Interfaza extends javax.swing.JFrame {
    
    /**
     * Creates new form Interfaza
     */
    public Interfaza() {
        initComponents();
        //Ocultar
        btnPuntoFijo.setVisible(false);
        btnNewtonRaphson.setVisible(false);
        btnSecante.setVisible(false);
        btnBiseccion.setVisible(false);
        btnSteffensen.setVisible(false);
        btnMuller.setVisible(false);
        btnOK1.setVisible(false);
        btnOK2.setVisible(false);
        btnOK3.setVisible(false);
        btnOK4.setVisible(false);
        btnOK5.setVisible(false);
        btnOK6.setVisible(false);
        btnGrafico.setVisible(false);
        //Pantalla
        this.getContentPane().setBackground(Color.ORANGE);
        this.setLocationRelativeTo(null);
    }
    //-----------Variables globales
    public static double a = 0; 
    public static double b = 0;
    public static double c = 0;
    public static double d = 0;
    public static double metd1 = 0;
    public static double metd2 = 0;
    public static double metd3a = 0;
    public static double metd3b = 0;
    public static double metd4a = 0;
    public static double metd4b = 0;
    public static double metd5 = 0;
    public static double metd6a = 0;
    public static double metd6b = 0;
    public static double metd6c = 0;
    public static int intentos = 0;
    public static double [] llena = {};
    public static int [] va  = {};
    //--------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCaja3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCaja4 = new javax.swing.JTextField();
        txtCaja2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCaja1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMetodoGrafico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla1 = new javax.swing.JTable();
        txtIntentos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnOK1 = new javax.swing.JButton();
        txtMetd1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPuntoFijo = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnOK2 = new javax.swing.JButton();
        txtMetd2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNewtonRaphson = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnOK3 = new javax.swing.JButton();
        txtMetd3b = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSecante = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtMetd3a = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnOK4 = new javax.swing.JButton();
        txtMetd4b = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblBiseccion = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtMetd4a = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnOK5 = new javax.swing.JButton();
        txtMetd5 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSteffensen = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnOK6 = new javax.swing.JButton();
        txtMetd6a = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMuller = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtMetd6b = new javax.swing.JTextField();
        txtMetd6c = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnPuntoFijo = new javax.swing.JButton();
        btnNewtonRaphson = new javax.swing.JButton();
        btnSecante = new javax.swing.JButton();
        btnSteffensen = new javax.swing.JButton();
        btnMuller = new javax.swing.JButton();
        btnBiseccion = new javax.swing.JButton();
        btnGrafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funciones no lineales - Aaron Jaramillo");

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESOLUCION DE FUNCIONES NO LINEALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        txtCaja3.setToolTipText("Ingrese un valor en C");

        jLabel4.setText("x      +");

        txtCaja4.setToolTipText("Ingrese un valor en D");

        txtCaja2.setToolTipText("Ingrese un valor en B");

        jLabel3.setText("x^2      +");

        txtCaja1.setToolTipText("Ingrese un valor en A");

        jLabel2.setText("x^3      +");

        btnMetodoGrafico.setText("Metodo Grafico");
        btnMetodoGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoGraficoActionPerformed(evt);
            }
        });

        tblTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "F(X)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabla1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblTabla1);

        txtIntentos.setToolTipText("Ingrese un valor en el Nº de intentos");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("A");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("B");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("C");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("D");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nº de Intentos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Metodo de Punto Fijo");

        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        txtMetd1.setToolTipText("Ingrese el valor de la Raiz");

        tblPuntoFijo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAIZ", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPuntoFijo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPuntoFijo);
        if (tblPuntoFijo.getColumnModel().getColumnCount() > 0) {
            tblPuntoFijo.getColumnModel().getColumn(0).setResizable(false);
            tblPuntoFijo.getColumnModel().getColumn(1).setResizable(false);
            tblPuntoFijo.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Raiz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnOK1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtMetd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5))
                            .addComponent(btnOK1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMetd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Metodo de Newton");

        btnOK2.setText("OK");
        btnOK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK2ActionPerformed(evt);
            }
        });

        txtMetd2.setToolTipText("Ingrese el valor de la Raiz");

        tblNewtonRaphson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAIZ", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNewtonRaphson.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblNewtonRaphson);
        if (tblNewtonRaphson.getColumnModel().getColumnCount() > 0) {
            tblNewtonRaphson.getColumnModel().getColumn(0).setResizable(false);
            tblNewtonRaphson.getColumnModel().getColumn(1).setResizable(false);
            tblNewtonRaphson.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel12.setText("Raphson");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Raiz");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOK2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMetd2)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnOK2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMetd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Metodo de la");

        btnOK3.setText("OK");
        btnOK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK3ActionPerformed(evt);
            }
        });

        txtMetd3b.setToolTipText("Ingrese el valor de X2");

        tblSecante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAIZ", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSecante.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblSecante);
        if (tblSecante.getColumnModel().getColumnCount() > 0) {
            tblSecante.getColumnModel().getColumn(0).setResizable(false);
            tblSecante.getColumnModel().getColumn(1).setResizable(false);
            tblSecante.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel14.setText("Secante");

        txtMetd3a.setToolTipText("Ingrese el valor de X1");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("X1                   X2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOK3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMetd3a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMetd3b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOK3)
                                    .addComponent(txtMetd3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMetd3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("Metodo de");

        btnOK4.setText("OK");
        btnOK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK4ActionPerformed(evt);
            }
        });

        txtMetd4b.setToolTipText("Ingrese el valor de X2");

        tblBiseccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAIZ", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBiseccion.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tblBiseccion);
        if (tblBiseccion.getColumnModel().getColumnCount() > 0) {
            tblBiseccion.getColumnModel().getColumn(0).setResizable(false);
            tblBiseccion.getColumnModel().getColumn(1).setResizable(false);
            tblBiseccion.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel16.setText("Biseccion");

        txtMetd4a.setToolTipText("Ingrese el valor de X1");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("X1                   X2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOK4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtMetd4a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMetd4b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOK4)
                                    .addComponent(txtMetd4a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMetd4b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Metodo de");

        btnOK5.setText("OK");
        btnOK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK5ActionPerformed(evt);
            }
        });

        txtMetd5.setToolTipText("Ingrese el valor de la Raiz");

        tblSteffensen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAIZ", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSteffensen.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblSteffensen);
        if (tblSteffensen.getColumnModel().getColumnCount() > 0) {
            tblSteffensen.getColumnModel().getColumn(0).setResizable(false);
            tblSteffensen.getColumnModel().getColumn(1).setResizable(false);
            tblSteffensen.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel18.setText("Steffensen");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Raiz");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOK5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(txtMetd5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnOK5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMetd5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Metodo de");

        btnOK6.setText("OK");
        btnOK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK6ActionPerformed(evt);
            }
        });

        txtMetd6a.setToolTipText("Ingrese el valor de X1");

        tblMuller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RAIZ", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMuller.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tblMuller);
        if (tblMuller.getColumnModel().getColumnCount() > 0) {
            tblMuller.getColumnModel().getColumn(0).setResizable(false);
            tblMuller.getColumnModel().getColumn(1).setResizable(false);
            tblMuller.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel20.setText("Muller");

        txtMetd6b.setToolTipText("Ingrese el valor de X2");

        txtMetd6c.setToolTipText("Ingrese el valor de X3");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("X1                  X2                   X3 ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOK6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtMetd6a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMetd6b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMetd6c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnOK6))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMetd6a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMetd6b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMetd6c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 204, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tablas completas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel8.setToolTipText("");

        btnPuntoFijo.setBackground(new java.awt.Color(255, 204, 102));
        btnPuntoFijo.setText("Punto Fijo");
        btnPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoFijoActionPerformed(evt);
            }
        });

        btnNewtonRaphson.setBackground(new java.awt.Color(255, 51, 0));
        btnNewtonRaphson.setText("Newton Rahpson");
        btnNewtonRaphson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewtonRaphsonActionPerformed(evt);
            }
        });

        btnSecante.setBackground(new java.awt.Color(255, 102, 102));
        btnSecante.setText("Secante");
        btnSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecanteActionPerformed(evt);
            }
        });

        btnSteffensen.setBackground(new java.awt.Color(102, 204, 255));
        btnSteffensen.setText("Steffensen");
        btnSteffensen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSteffensenActionPerformed(evt);
            }
        });

        btnMuller.setBackground(new java.awt.Color(0, 51, 255));
        btnMuller.setText("Muller");
        btnMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMullerActionPerformed(evt);
            }
        });

        btnBiseccion.setBackground(new java.awt.Color(204, 102, 255));
        btnBiseccion.setText("Biseccion");
        btnBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiseccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBiseccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPuntoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnNewtonRaphson)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnSteffensen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSecante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMuller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSecante)
                    .addComponent(btnPuntoFijo)
                    .addComponent(btnNewtonRaphson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMuller)
                    .addComponent(btnBiseccion)
                    .addComponent(btnSteffensen))
                .addGap(41, 41, 41))
        );

        btnGrafico.setText("Grafico");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMetodoGrafico)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCaja2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtCaja3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtCaja4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMetodoGrafico)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGrafico))))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodoGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoGraficoActionPerformed
        // TODO add your handling code here:
        //Llama el valor que se ingresa a la caja
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true){
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());       

            DefaultTableModel modelo = (DefaultTableModel) tblTabla1.getModel();

            limpiarTabla(modelo, tblTabla1);
            
            //txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));

            llena = new double[9];
            va = new int[9];

            for(int i=0, j=-4; i<llena.length; i++, j++)
            {
                va[i]=j;
                //llena[i]=(a*Math.pow(j, 3))+(b*Math.pow(j, 2))+(c*j)+d;
                llena[i]=FuncionEntrante(a, b, c, d, j);
            }
            //Buscar que 
            /*int [] pintarposicion = new int [2];
            for (int i = 0; i < llena.length-1; i++) {
                if ( (llena[i] <= 0 && llena[i+1] >= 0) || (llena[i] >= 0 && llena[i+1] <= 0)) {
                    pintarposicion[0]=i;
                    pintarposicion[1]=i+1;
                }
            }*/

            Object [] yano = new Object[2];
            for(int i=0; i<9; i++)
            {                
                yano[0]=va[i];
                yano[1]=llena[i];
                
                modelo.addRow(yano);
            }
            
        }
        btnOK1.setVisible(true);
        btnOK2.setVisible(true);
        btnOK3.setVisible(true);
        btnOK4.setVisible(true);
        btnOK5.setVisible(true);
        btnOK6.setVisible(true);
        btnGrafico.setVisible(true);
        //Establece valores en la caja
        //txtCaja3.setText(Integer.toString(a+b));
    }//GEN-LAST:event_btnMetodoGraficoActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        // TODO add your handling code here:
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText(), txtMetd1.getText(), txtIntentos.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D", "Raiz", "Intentos"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true)
        {
            metd1 = Double.parseDouble(txtMetd1.getText());
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblPuntoFijo.getModel();
            
            limpiarTabla(modelo, tblPuntoFijo);

            //Agregar por usuario el numero de intentos
            //int intentos = 100
            txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));
            intentos = Integer.parseInt(txtIntentos.getText());
            int []n1 = new int[intentos];
            double [] xR1 = new double[intentos];
            double [] fxRi = new double[intentos];
            double [] error1 = new double[intentos];
            double [] fxf1 = new double[intentos];
            double calculoa = 0;
            double calculob = 0;
            double calculoc = 0;

            for(int i=0; i<intentos; i++)
            {
                n1[i]=(i+1);
                if(i==0)
                {
                    xR1[i]=metd1;
                }
                else
                {
                    xR1[i]=fxRi[i-1];
                }
                calculob=b*Math.pow(xR1[i], 2);
                calculoc=c*xR1[i];
                calculoa=(-1*(calculob+calculoc+d))/a;
                fxRi[i]=Math.cbrt(calculoa);
                fxf1[i]=FuncionEntrante(a, b, c, d, xR1[i]);
                if(i==0)
                {
                    error1[i]=0;
                }
                else
                {
                    error1[i]=Math.abs(fxRi[i]-fxRi[i-1]);
                }
            }
            //Imprimir tabla
            imprimirTabla(n1, xR1, fxf1, error1, intentos, modelo);
            btnPuntoFijo.setVisible(true);
        }
        //--termina
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void btnOK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK2ActionPerformed
        // TODO add your handling code here:
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText(), txtMetd2.getText(), txtIntentos.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D", "Raiz", "Intentos"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true)
        {
            metd2 = Double.parseDouble(txtMetd2.getText());
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblNewtonRaphson.getModel();

            limpiarTabla(modelo, tblNewtonRaphson);
            
            txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));

            intentos = Integer.parseInt(txtIntentos.getText());
            int []n1 = new int[intentos];
            double [] xI1 = new double[intentos];
            double [] fXr1 = new double[intentos];
            double [] fDXr1 = new double[intentos];
            double [] xR1 = new double[intentos];
            double [] error1 = new double[intentos];
            for(int i=0; i<intentos; i++)
            {
                n1[i]=(i+1);
                if(i==0)
                {
                    xI1[i]=metd2;
                }
                else
                {
                    xI1[i]=xR1[i-1];
                }
                //fXr1[i]=(a*Math.pow(xI1[i], (double)3))+(b*Math.pow(xI1[i], (double)2))+(c*xI1[i])+d;
                fXr1[i]=FuncionEntrante(a, b, c, d, xI1[i]);
                //fDXr1[i]=(3*a*Math.pow(xI1[i], (double)2))+(2*b*xI1[i])+c;
                fDXr1[i]=FuncionDerivada(a, b, c, xI1[i]);
                xR1[i]=xI1[i]-(fXr1[i]/fDXr1[i]);  
                if(i==0)
                {
                    error1[i]=0;
                }
                else
                {
                    error1[i]=Math.abs(fXr1[i]-fXr1[i-1]);
                }
            }
            
            //Imprimir tabla
            imprimirTabla(n1, xI1, fXr1, error1, intentos, modelo);
            btnNewtonRaphson.setVisible(true);
        }
        //---termina
    }//GEN-LAST:event_btnOK2ActionPerformed

    private void btnOK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK3ActionPerformed
        // TODO add your handling code here:
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText(), txtMetd3a.getText(), txtMetd3b.getText(), txtIntentos.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D", "X1", "X2", "Intentos"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true)
        {
            metd3a = Double.parseDouble(txtMetd3a.getText());
            metd3b = Double.parseDouble(txtMetd3b.getText());
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblSecante.getModel();

            limpiarTabla(modelo, tblSecante);
            
            txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));
            
            //Variables
            intentos = Integer.parseInt(txtIntentos.getText());
            int []n = new int[intentos];
            double [] xo = new double[intentos];
            double [] xi = new double[intentos];
            double [] x2 = new double[intentos];
            double [] fxo = new double[intentos];
            double [] fxi = new double[intentos];
            double [] fx2 = new double[intentos];
            double [] error = new double[intentos];
            double calculo1, calculo2, calculo3;
            for(int i=0; i<intentos; i++)
            {
                n[i]=(i+1);
                if(i==0)
                {
                    xo[i]=metd3a;
                    xi[i]=metd3b;
                }
                else
                {
                    xo[i]=xi[i-1];
                    xi[i]=x2[i-1];
                }

                fxo[i]=FuncionEntrante(a, b, c, d, xo[i]);
                fxi[i]=FuncionEntrante(a, b, c, d, xi[i]);
                calculo1=((double)xi[i]-(double)xo[i])*(double)fxi[i];
                calculo2=(double)fxi[i]-(double)fxo[i];
                calculo3=(double)calculo1/(double)calculo2;
                x2[i]=xi[i]-(double)calculo3;
                fx2[i]=FuncionEntrante(a, b, c, d, x2[i]);

                if(i==0)
                {
                    error[i]=0;
                }
                else
                {
                    error[i]=Math.abs(fx2[i]-fx2[i-1]);
                }
            }

            //Imprimir tabla
            imprimirTabla(n, x2, fx2, error, intentos, modelo);
            btnSecante.setVisible(true);
        }
        //----termina
    }//GEN-LAST:event_btnOK3ActionPerformed

    private void btnOK4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK4ActionPerformed
        // TODO add your handling code here:
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText(), txtMetd4a.getText(), txtMetd4b.getText(), txtIntentos.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D", "X1", "X2", "Intentos"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true)
        {
            metd4a = Double.parseDouble(txtMetd4a.getText());
            metd4b = Double.parseDouble(txtMetd4b.getText());
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblBiseccion.getModel();

            limpiarTabla(modelo, tblBiseccion);
            
            txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));
            
            //Variables
            intentos = Integer.parseInt(txtIntentos.getText());
            int []n = new int[intentos];
            double [] XI = new double[intentos];
            double [] XD = new double[intentos];
            double [] XM = new double[intentos];
            double [] FXI = new double[intentos];
            double [] FXD = new double[intentos];
            double [] FXM = new double[intentos];
            double [] error = new double[intentos];
            double calculo1, calculo2, calculo3;
            for(int i=0; i<intentos; i++)
            {
                n[i]=(i+1);
                if(i==0)
                {
                    XI[i]=metd4a;
                    XD[i]=metd4b;
                }
                else
                {
                    if(FXM[i-1]<0)
                    {
                        XI[i]=XM[i-1];
                        XD[i]=XD[i-1];
                    }
                    else
                    {
                        XI[i]=XI[i-1];
                        XD[i]=XM[i-1];
                    }
                }

                FXI[i]=FuncionEntrante(a, b, c, d, XI[i]);
                FXD[i]=FuncionEntrante(a, b, c, d, XD[i]);
                calculo1=((double)XD[i]-(double)XI[i])*(double)FXD[i];
                calculo2=(double)FXD[i]-(double)FXI[i];
                calculo3=(double)calculo1/(double)calculo2;
                XM[i]=XD[i]-(double)calculo3;
                FXM[i]=FuncionEntrante(a, b, c, d, XM[i]);

                if(i==0)
                {
                    error[i]=0;
                }
                else
                {
                    error[i]=Math.abs(FXM[i]-FXM[i-1]);
                }
            }
            
            //Imprimir tabla
            imprimirTabla(n, XM, FXM, error, intentos, modelo);
            btnBiseccion.setVisible(true);
        }
        //----termina
    }//GEN-LAST:event_btnOK4ActionPerformed

    private void btnOK5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK5ActionPerformed
        // TODO add your handling code here:
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText(), txtMetd5.getText(), txtIntentos.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D", "Raiz", "Intentos"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true)
        {
            metd5 = Double.parseDouble(txtMetd5.getText());
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblSteffensen.getModel();

            limpiarTabla(modelo, tblSteffensen);
            
            txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));

            intentos = Integer.parseInt(txtIntentos.getText());
            int []n = new int[intentos];
            double [] x0 = new double[intentos];
            double [] x1 = new double[intentos];
            double [] x2 = new double[intentos];
            double [] xr = new double[intentos];
            double [] fx0 = new double[intentos];
            double [] fx1 = new double[intentos];
            double [] fxr = new double[intentos];
            double [] fdx0 = new double[intentos];
            double [] fdx1 = new double[intentos];
            double [] error = new double[intentos];

            double calculoa, calculob, calculoc, calculod;

            for(int i=0; i<intentos; i++)
            {
                n[i]=(i+1);
                if(i==0)
                {
                    x0[i]=metd5;
                }
                else
                {
                    x0[i]=xr[i-1];
                }
                fx0[i]=FuncionEntrante(a, b, c, d, x0[i]);
                fdx0[i]=FuncionDerivada(a, b, c, x0[i]);
                x1[i]=FuncionSacarOtraX(x0[i], fx0[i], fdx0[i]);

                fx1[i]=FuncionEntrante(a, b, c, d, x1[i]);
                fdx1[i]=FuncionDerivada(a, b, c, x1[i]);
                x2[i]=FuncionSacarOtraX(x1[i], fx1[i], fdx1[i]);

                calculoa=(double)x1[i]-(double)x0[i];
                calculob=Math.pow((double)calculoa, 2);
                calculoc=(double)x2[i]-(2*(double)x1[i])+(double)x0[i];
                calculod=x0[i]-((double)calculob/(double)calculoc);
                xr[i]=(double)calculod;
                fxr[i]=FuncionEntrante(a, b, c, d, xr[i]);
                if(i==0)
                {
                    error[i]=0;
                }
                else
                {
                    error[i]=Math.abs(xr[i]-xr[i-1]);
                }
            }
            
            //imprimir tabla
            imprimirTabla(n, xr, fxr, error, intentos, modelo);
            btnSteffensen.setVisible(true);
        }
        //---termina
    }//GEN-LAST:event_btnOK5ActionPerformed

    private void btnOK6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK6ActionPerformed
        // TODO add your handling code here:
        String [] mi_Baul = {txtCaja1.getText(), txtCaja2.getText(), txtCaja3.getText(), txtCaja4.getText(), txtMetd6a.getText(), txtMetd6b.getText(), txtMetd6c.getText(), txtIntentos.getText()};
        String [] mi_Biblioteca = {"A", "B", "C", "D", "X1", "X2", "X3", "Intentos"};
        if(estaLleno(mi_Baul, mi_Biblioteca)!=true)
        {
            metd6a = Double.parseDouble(txtMetd6a.getText());
            metd6b = Double.parseDouble(txtMetd6b.getText());
            metd6c = Double.parseDouble(txtMetd6c.getText());
            a = Double.parseDouble(txtCaja1.getText());
            b = Double.parseDouble(txtCaja2.getText());
            c = Double.parseDouble(txtCaja3.getText());
            d = Double.parseDouble(txtCaja4.getText());

            DefaultTableModel modelo = (DefaultTableModel) tblMuller.getModel();
            
            limpiarTabla(modelo, tblMuller);
            
            txtIntentos.setText(Integer.toString(Math.abs(Integer.parseInt(txtIntentos.getText()))));
            
            //Variables
            intentos = Integer.parseInt(txtIntentos.getText());
            int []n = new int[intentos];
            double [] x0 = new double[intentos];
            double [] x1 = new double[intentos];
            double [] x2 = new double[intentos];
            double [] xr = new double[intentos];
            double [] f0 = new double[intentos];
            double [] f1 = new double[intentos];
            double [] f2 = new double[intentos];
            double [] fx1x0 = new double[intentos];
            double [] fx2x1 = new double[intentos];
            double [] fx2x1x0 = new double[intentos];
            double [] fxr = new double[intentos];
            double [] varc = new double[intentos];
            double [] varb = new double[intentos];
            double [] vara = new double[intentos];
            double [] fd1 = new double[intentos];
            double [] fd2 = new double[intentos];
            double [] error = new double[intentos];
            double [] mini = new double[intentos]; 

            int eleccion=0;
            double calculoa=0;
            for(int i=0; i<intentos; i++)
            {
                n[i]=(i+1);
                if(i==0)
                {
                    x0[i]=metd6a;
                    x1[i]=metd6b;
                    x2[i]=metd6c;
                }
                else
                {
                    x0[i]=x1[i-1];
                    x1[i]=x2[i-1];
                    x2[i]=xr[i-1];
                }

                f0[i]=FuncionEntrante(a, b, c, d, x0[i]);
                f1[i]=FuncionEntrante(a, b, c, d, x1[i]);
                f2[i]=FuncionEntrante(a, b, c, d, x2[i]);
                fx1x0[i]=((double)f1[i]-(double)f0[i])/((double)x1[i]-(double)x0[i]);
                fx2x1[i]=((double)f2[i]-(double)f1[i])/((double)x2[i]-(double)x1[i]);
                fx2x1x0[i]=(double)fx2x1[i]-(double)fx1x0[i];
                varc[i]=(double)fx2x1x0[i];
                varb[i]=(double)fx2x1[i]-(((double)x2[i]+(double)x1[i])*varc[i]);
                vara[i]=(double)f2[i]-(double)x2[i]*((double)fx2x1[i]-((double)x1[i]*(double)varc[i]));
                calculoa=Math.sqrt((double)Math.pow(varb[i], 2)-((double)4*(double)vara[i]*(double)varc[i]));
                fd1[i]=-(double)varb[i]+(double)calculoa;
                fd2[i]=-(double)varb[i]-(double)calculoa;

                if(Math.abs((double)fd2[i])<Math.abs((double)fd1[i]))
                {
                    mini[i]=Math.abs((double)fd2[i]);
                    if(n[i]==1)
                    {
                        eleccion=1;
                    }
                    //xr[i]=((double)2*(double)vara[i])/(double)fd2[i];
                }
                else
                {
                    mini[i]=Math.abs((double)fd1[i]);
                    if(n[i]==1)
                    {
                        eleccion=2;
                    }
                    //xr[i]=((double)2*(double)vara[i])/(double)fd1[i];
                }

                switch(eleccion){
                    case 1:
                        xr[i]=((double)2*(double)vara[i])/(double)fd2[i];
                        break;
                    case 2:
                        xr[i]=((double)2*(double)vara[i])/(double)fd1[i];
                        break;
                }

                fxr[i]=FuncionEntrante(a, b, c, d, xr[i]);

                if(i==0)
                {
                    error[i]=0;
                }
                else
                {
                    error[i]=Math.abs(xr[i]-xr[i-1]);
                }
            }
            //Mostrar en la tabla
            imprimirTabla(n, xr, fxr, error, intentos, modelo);
            btnMuller.setVisible(true);
        }
        //----termina
    }//GEN-LAST:event_btnOK6ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        //Limpiar cajas de texto
        txtCaja1.setText("");
        txtCaja2.setText("");
        txtCaja3.setText("");
        txtCaja4.setText("");
        txtIntentos.setText("");
        txtMetd1.setText("");
        txtMetd2.setText("");
        txtMetd3a.setText("");
        txtMetd3b.setText("");
        txtMetd4a.setText("");
        txtMetd4b.setText("");
        txtMetd5.setText("");
        txtMetd6a.setText("");
        txtMetd6b.setText("");
        txtMetd6c.setText("");
        
        //Ocultar
        btnPuntoFijo.setVisible(false);
        btnNewtonRaphson.setVisible(false);
        btnSecante.setVisible(false);
        btnBiseccion.setVisible(false);
        btnSteffensen.setVisible(false);
        btnMuller.setVisible(false);
        btnOK1.setVisible(false);
        btnOK2.setVisible(false);
        btnOK3.setVisible(false);
        btnOK4.setVisible(false);
        btnOK5.setVisible(false);
        btnOK6.setVisible(false);
        btnGrafico.setVisible(false);
        
        //limpiar tablas
        DefaultTableModel modelo1 = (DefaultTableModel) tblTabla1.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) tblBiseccion.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) tblMuller.getModel();
        DefaultTableModel modelo4 = (DefaultTableModel) tblNewtonRaphson.getModel();
        DefaultTableModel modelo5 = (DefaultTableModel) tblPuntoFijo.getModel();
        DefaultTableModel modelo6 = (DefaultTableModel) tblSecante.getModel();
        DefaultTableModel modelo7 = (DefaultTableModel) tblSteffensen.getModel();
        
        limpiarTabla(modelo1, tblTabla1);
        limpiarTabla(modelo2, tblBiseccion);
        limpiarTabla(modelo3, tblMuller);
        limpiarTabla(modelo4, tblNewtonRaphson);
        limpiarTabla(modelo5, tblPuntoFijo);
        limpiarTabla(modelo6, tblSecante);
        limpiarTabla(modelo7, tblSteffensen);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSteffensenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSteffensenActionPerformed
        // TODO add your handling code here:
        Steffensen st = new Steffensen();
            st.setVisible(true);
    }//GEN-LAST:event_btnSteffensenActionPerformed

    private void btnPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoFijoActionPerformed
        // TODO add your handling code here:
        PuntoFijo pj = new PuntoFijo();
            pj.setVisible(true);
    }//GEN-LAST:event_btnPuntoFijoActionPerformed

    private void btnNewtonRaphsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewtonRaphsonActionPerformed
        // TODO add your handling code here:
        NewtonRaphson nr = new NewtonRaphson();
            nr.setVisible(true);
    }//GEN-LAST:event_btnNewtonRaphsonActionPerformed

    private void btnSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecanteActionPerformed
        // TODO add your handling code here:
        Secante sc = new Secante();
            sc.setVisible(true);
    }//GEN-LAST:event_btnSecanteActionPerformed

    private void btnBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiseccionActionPerformed
        // TODO add your handling code here:
        Biseccion bi = new Biseccion();
            bi.setVisible(true);
    }//GEN-LAST:event_btnBiseccionActionPerformed

    private void btnMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMullerActionPerformed
        // TODO add your handling code here:
        Muller mu = new Muller();
            mu.setVisible(true);
    }//GEN-LAST:event_btnMullerActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        // TODO add your handling code here:
        Grafico grafico = new Grafico();
        grafico.setVisible(true);
    }//GEN-LAST:event_btnGraficoActionPerformed

    public static void limpiarTabla(DefaultTableModel modelo, JTable tabla)
    {
        for (int i = tabla.getRowCount() -1; i >= 0; i--){
                    modelo.removeRow(i);
            }
    }
    
    public static double FuncionEntrante(double a, double b, double c, double d, double x){
        double resultado=0;
        resultado=(a*Math.pow(x, (double)3))+(b*Math.pow(x, (double)2))+(c*x)+d;
        return resultado;
    }
    
    public static double FuncionDerivada(double a, double b, double c, double x){
        double resultado=0;
        resultado=(3*a*Math.pow(x, (double)2))+(2*b*x)+c;
        return resultado;
    }
    
    public static double FuncionSacarOtraX(double a, double b, double c){
        double resultado=0;
        resultado=(double)a-((double)b/(double)c);
        return resultado;
    }
    
    public static String CKambio(Double num){
        //Para mayores de E-3
	DecimalFormat dh = new DecimalFormat("##0.########");
	//Para menores de E-3
	DecimalFormat df = new DecimalFormat("0.###E0");
        
        String cambio="";
        if(num==0){
                cambio = Double.toString(num);
            }else if( (num > 10E-3) || (num < -10E-3) ){
                cambio=dh.format(num);
            }else{
                cambio=df.format(num);
            }
        return cambio;
    }
    
    public static void imprimirTabla(int[] n, double[] sandia, double[] naranja, double[] error, int intentos, DefaultTableModel modelo)
    {
        //Mostrar en la tabla
        Object [] soda = new Object[3];

        for(int i=0; i<intentos; i++)
        {
            if(n[i]!=1 && Math.abs(naranja[i])< 1E-7)
            {
                soda[0]=CKambio(sandia[i]);
                soda[1]=CKambio(naranja[i]);
                soda[2]=CKambio(error[i]);
                //Añadir fila
                modelo.addRow(soda);
                break;
            }
            else if(n[i]==intentos)
            {
                JOptionPane.showMessageDialog(null, "No converge porque la funcion no es  menor a E-7", "NO CONVERGE", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    public static boolean estaLleno(String[] Mi_Baul, String[] Mi_Biblioteca){
        String [] caja = Mi_Baul;
        String [] nombre = Mi_Biblioteca;
        String tina="";
        Boolean verdad=false;
        for(int i=0; i<caja.length; i++)
        {
            if(caja[i].length()==0 || noNumero(caja[i])==true)
            {
            	tina+=nombre[i];
            	if(i!=(caja.length-1))
            	{
            		tina+=" ";
            	}
                verdad=true;
            }
        }
        
        if(verdad==true)
        {
            JOptionPane.showMessageDialog(null, "No se ha ingresado un valor numerico en "+tina, "ERROR", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }
    
    public static boolean noNumero(String numero)
    {
        try {
            Double comprobar = Double.parseDouble(numero);
        } catch (Exception e) {
            return true;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiseccion;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMetodoGrafico;
    private javax.swing.JButton btnMuller;
    private javax.swing.JButton btnNewtonRaphson;
    private javax.swing.JButton btnOK1;
    private javax.swing.JButton btnOK2;
    private javax.swing.JButton btnOK3;
    private javax.swing.JButton btnOK4;
    private javax.swing.JButton btnOK5;
    private javax.swing.JButton btnOK6;
    private javax.swing.JButton btnPuntoFijo;
    private javax.swing.JButton btnSecante;
    private javax.swing.JButton btnSteffensen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblBiseccion;
    private javax.swing.JTable tblMuller;
    private javax.swing.JTable tblNewtonRaphson;
    private javax.swing.JTable tblPuntoFijo;
    private javax.swing.JTable tblSecante;
    private javax.swing.JTable tblSteffensen;
    private javax.swing.JTable tblTabla1;
    private javax.swing.JTextField txtCaja1;
    private javax.swing.JTextField txtCaja2;
    private javax.swing.JTextField txtCaja3;
    private javax.swing.JTextField txtCaja4;
    private javax.swing.JTextField txtIntentos;
    private javax.swing.JTextField txtMetd1;
    private javax.swing.JTextField txtMetd2;
    private javax.swing.JTextField txtMetd3a;
    private javax.swing.JTextField txtMetd3b;
    private javax.swing.JTextField txtMetd4a;
    private javax.swing.JTextField txtMetd4b;
    private javax.swing.JTextField txtMetd5;
    private javax.swing.JTextField txtMetd6a;
    private javax.swing.JTextField txtMetd6b;
    private javax.swing.JTextField txtMetd6c;
    // End of variables declaration//GEN-END:variables
}
