/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla;

import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aaron
 */
public class NewtonRaphson extends javax.swing.JFrame {

    /**
     * Creates new form PuntoFijo
     */
    public NewtonRaphson() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Hacer el metodo
        int intentos;
        double a, b, c, d, raiz;
        Interfaza inter = new Interfaza();
        a=inter.a;
        b=inter.b;
        c=inter.c;
        d=inter.d;
        raiz=inter.metd2;
        intentos=inter.intentos;
        //COdigo para hacer la tabla
        DefaultTableModel modelo1 = (DefaultTableModel) tblFormula1.getModel();
        hacertabla(intentos, raiz, a, b, c, d, modelo1, txtInformacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFormula1 = new javax.swing.JTable();
        txtInformacion = new javax.swing.JLabel();

        setTitle("Newton - Aaron Jaramillo");

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Newton Rhapson");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblFormula1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "xi", "fxr", "f'xr", "xr", "Error"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFormula1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblFormula1);

        txtInformacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void hacertabla(int intentos, double raiz, double a, double b, double c, double d, DefaultTableModel modelo, JLabel info){
        int []n1 = new int[intentos];
        double [] xI1 = new double[intentos];
        double [] fXr1 = new double[intentos];
        double [] fDXr1 = new double[intentos];
        double [] xR1 = new double[intentos];
        double [] error1 = new double[intentos];
        for(int i=0; i<intentos; i++)
        {
            n1[i]=(i+1);
            if(i==0)
            {
                xI1[i]=raiz;
            }
            else
            {
                xI1[i]=xR1[i-1];
            }
            fXr1[i]=(a*Math.pow(xI1[i], (double)3))+(b*Math.pow(xI1[i], (double)2))+(c*xI1[i])+d;
            fDXr1[i]=(3*a*Math.pow(xI1[i], (double)2))+(2*b*xI1[i])+c;
            xR1[i]=xI1[i]-(fXr1[i]/fDXr1[i]);  
            if(i==0)
            {
                error1[i]=0;
            }
            else
            {
                error1[i]=Math.abs(fXr1[i]-fXr1[i-1]);
            }
        }
        
        Object []yano = new Object[6];
        //Añadir condiccion para que salga de este formato solo caundo sean menores  E-3
        //Poner condiccion cuando se encuentre la raiz, solo me muestre los resultados hasta ahi
        
        //Para mayores de E-3
	//DecimalFormat dh = new DecimalFormat("##0.####");
	//Para menores de E-3
	//DecimalFormat df = new DecimalFormat("0.####E0");
        
        for(int i=0; i<intentos; i++)
        {
            yano[0]=n1[i];
            yano[1]=CKambio(xI1[i]);
            yano[2]=CKambio(fXr1[i]);
            yano[3]=CKambio(fDXr1[i]);
            yano[4]=CKambio(xR1[i]);
            yano[5]=CKambio(error1[i]);
            //Añadir fila
            modelo.addRow(yano);
            //Romper bucle
            //if(n1[i]!=1 && fXr1[i]==0)
            //if(n1[i]!=1 && error1[i]==0)
            if(n1[i]!=1 && Math.abs(fXr1[i])< 1E-7)
            {
                break;
            }
            else if(n1[i]==intentos)
            {
                info.setText("No converge porque la funcion no es  menor a E-7");
                //JOptionPane.showMessageDialog(null, "No converge porque la funcion no es  menor a E-7", "NO CONVERGE", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
     public static String CKambio(Double num){
        //Para mayores de E-3
	DecimalFormat dh = new DecimalFormat("##0.########");
	//Para menores de E-3
	DecimalFormat df = new DecimalFormat("0.###E0");
        
        String cambio="";
        if(num==0){
                cambio = Double.toString(num);
            }else if( (num > 10E-3) || (num < -10E-3) ){
                cambio=dh.format(num);
            }else{
                cambio=df.format(num);
            }
        return cambio;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewtonRaphson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewtonRaphson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFormula1;
    private javax.swing.JLabel txtInformacion;
    // End of variables declaration//GEN-END:variables
}
