/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aaron
 */
public class PuntoFijo extends javax.swing.JFrame {

    /**
     * Creates new form PuntoFijo
     */
    public PuntoFijo() {
        initComponents();
        //this.getContentPane().setBackground(Color.yellow);
        this.setLocationRelativeTo(null);
        //Hacer el metodo
        int intentos;
        double a, b, c, d, raiz;
        Interfaza inter = new Interfaza();
        a=inter.a;
        b=inter.b;
        c=inter.c;
        d=inter.d;
        raiz=inter.metd1;
        intentos=inter.intentos;
        //COdigo para hacer la tabla
        DefaultTableModel modelo1 = (DefaultTableModel) tblFormula1.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) tblFormula2.getModel();
        hacertabla(intentos, 1, raiz, a, b, c, d, modelo1, txtInformacion1, txtInformacion2);
        hacertabla(intentos, 2, raiz, a, b, c, d, modelo2, txtInformacion1, txtInformacion2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFormula1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblFormula2 = new javax.swing.JTable();
        txtInformacion1 = new javax.swing.JLabel();
        txtInformacion2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Punto Fijo - Aaron Jaramillo");

        jPanel2.setBackground(java.awt.Color.yellow);
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Punto Fijo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tblFormula1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "XR", "F(XR)", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblFormula1);
        if (tblFormula1.getColumnModel().getColumnCount() > 0) {
            tblFormula1.getColumnModel().getColumn(0).setResizable(false);
            tblFormula1.getColumnModel().getColumn(1).setResizable(false);
            tblFormula1.getColumnModel().getColumn(2).setResizable(false);
            tblFormula1.getColumnModel().getColumn(3).setResizable(false);
            tblFormula1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Formula 1");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Formula 2");

        tblFormula2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "XR", "F(XR)", "F(X)", "ERROR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblFormula2);
        if (tblFormula2.getColumnModel().getColumnCount() > 0) {
            tblFormula2.getColumnModel().getColumn(0).setResizable(false);
            tblFormula2.getColumnModel().getColumn(1).setResizable(false);
            tblFormula2.getColumnModel().getColumn(2).setResizable(false);
            tblFormula2.getColumnModel().getColumn(3).setResizable(false);
            tblFormula2.getColumnModel().getColumn(4).setResizable(false);
        }

        txtInformacion1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtInformacion1.setForeground(new java.awt.Color(255, 51, 51));
        txtInformacion1.setToolTipText("");

        txtInformacion2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtInformacion2.setForeground(new java.awt.Color(255, 51, 51));
        txtInformacion2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtInformacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtInformacion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInformacion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void hacertabla(int intentos, int decision, double raiz, double a, double b, double c, double d, DefaultTableModel modelo, JLabel info1, JLabel info2){
        int []n1 = new int[intentos];
        double [] xR1 = new double[intentos];
        double [] fxRi = new double[intentos];
        double [] error1 = new double[intentos];
        double [] fxf1 = new double[intentos];
        double calculoa = 0;
        double calculob = 0;
        double calculoc = 0;
        for(int i=0; i<intentos; i++)
        {
            if(i==0)
            {
                n1[i]=(i+1);
                xR1[i]=raiz;
                
                switch(decision){
                    case 1:
                        fxRi[i]=-d/((a*Math.pow(xR1[i], 2))+(b*xR1[i])+c);
                        break;
                    case 2:
                        calculob=b*Math.pow(xR1[i], 2);
                        calculoc=c*xR1[i];
                        calculoa=(-1*(calculob+calculoc+d))/a;
                        fxRi[i]=Math.cbrt(calculoa);
                        break;
                }
                
                error1[i]=0;
                fxf1[i]=(a*Math.pow(xR1[i], (double)3))+(b*Math.pow(xR1[i], (double)2))+(c*xR1[i])+d;
            }
            else
            {
                n1[i]=(i+1);
                xR1[i]=fxRi[i-1];
                
                 switch(decision){
                    case 1:
                        fxRi[i]=-d/((a*Math.pow(xR1[i], 2))+(b*xR1[i])+c);
                        break;
                    case 2:
                        calculob=b*Math.pow(xR1[i], 2);
                        calculoc=c*xR1[i];
                        calculoa=(-1*(calculob+calculoc+d))/a;
                        fxRi[i]=Math.cbrt(calculoa);
                        break;
                }
                 
                error1[i]=Math.abs(fxRi[i]-fxRi[i-1]);
                fxf1[i]=(a*Math.pow(xR1[i], (double)3))+(b*Math.pow(xR1[i], (double)2))+(c*xR1[i])+d;
            }
            
        }
        
        Object []yano = new Object[intentos];
        //Añadir condiccion para que salga de este formato solo caundo sean menores  E-3
        //Poner condiccion cuando se encuentre la raiz, solo me muestre los resultados hasta ahi
        
        //Para mayores de E-3
	//DecimalFormat dh = new DecimalFormat("##0.####");
	//Para menores de E-3
	//DecimalFormat df = new DecimalFormat("0.####E0");
        
        for(int i=0; i<intentos; i++)
        {
            yano[0]=n1[i];
            yano[1]=CKambio(xR1[i]);
            yano[2]=CKambio(fxRi[i]);
            yano[3]=CKambio(fxf1[i]);
            yano[4]=CKambio(error1[i]);
            
            //Añadir fila
            modelo.addRow(yano);
            if(n1[i]!=1 && Math.abs(fxf1[i])< 1E-7)
            {
                break;
            }
            else if(n1[i]==intentos)
            {
                switch(decision){
                    case 1:
                        info1.setText("No converge porque la funcion no es  menor a E-7");
                        info2.setText("");
                        break;
                    case 2:
                        info1.setText("");
                        info2.setText("No converge porque la funcion no es  menor a E-7");
                        break;
                }
                //JOptionPane.showMessageDialog(null, "No converge porque la funcion no es  menor a E-7", "NO CONVERGE", JOptionPane.WARNING_MESSAGE);
            }
            /*
            //Romper bucle
            if(n1[i]!=1 && error1[i]==0)
            {
                yano[0]=n1[i];
                yano[1]=xR1[i];
                yano[2]=fxRi[i];
                yano[3]=error1[i];
                yano[4]=fxf1[i];
                //Añadir fila
                modelo.addRow(yano);
                break;
            }
            else
            {
                yano[0]=n1[i];
                yano[1]=dh.format(xR1[i]);
                yano[2]=dh.format(fxRi[i]);

                //Primerra condicccion
                if(error1[i]==0){
                    yano[3]=error1[i];
                }else if( (error1[i] > 10E-3) || (error1[i] < -10E-3) ){
                    yano[3]=dh.format(error1[i]);
                }else{
                    yano[3]=df.format(error1[i]);
                }
                //Segunda condicccion
                if( (fxf1[i] > 10E-3) || (fxf1[i] < -10E-3) ){
                    yano[4]=dh.format(fxf1[i]);
                }else{
                    yano[4]=df.format(fxf1[i]);
                }
                //Añadir fila
                modelo.addRow(yano);
            }*/
        }
    }
    
    public static String CKambio(Double num){
        //Para mayores de E-3
	DecimalFormat dh = new DecimalFormat("##0.########");
	//Para menores de E-3
	DecimalFormat df = new DecimalFormat("0.###E0");
        
        String cambio="";
        if(num==0){
                cambio = Double.toString(num);
            }else if( (num > 10E-3) || (num < -10E-3) ){
                cambio=dh.format(num);
            }else{
                cambio=df.format(num);
            }
        return cambio;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuntoFijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuntoFijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuntoFijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuntoFijo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuntoFijo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tblFormula1;
    private javax.swing.JTable tblFormula2;
    private javax.swing.JLabel txtInformacion1;
    private javax.swing.JLabel txtInformacion2;
    // End of variables declaration//GEN-END:variables
}
