/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla;

import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aaron
 */
public class Secante extends javax.swing.JFrame {

    /**
     * Creates new form PuntoFijo
     */
    public Secante() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Hacer el metodo
        int intentos;
        double a, b, c, d, raiz1, raiz2;
        Interfaza inter = new Interfaza();
        a=inter.a;
        b=inter.b;
        c=inter.c;
        d=inter.d;
        raiz1=inter.metd3a;
        raiz2=inter.metd3b;
        intentos=inter.intentos;
        //COdigo para hacer la tabla
        DefaultTableModel modelo1 = (DefaultTableModel) tblFormula1.getModel();
        hacertabla(intentos, raiz1, raiz2, a, b, c, d, modelo1, txtInformacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFormula1 = new javax.swing.JTable();
        txtInformacion = new javax.swing.JLabel();

        setTitle("Secante - Aaron Jaramillo");

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Secante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblFormula1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "xo", "xi", "fxo", "fxi", "x2", "fx2", "Error"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFormula1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblFormula1);

        txtInformacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static double FuncionEntrante(double a, double b, double c, double d, double x){
        double resultado=0;
        resultado=(a*Math.pow(x, (double)3))+(b*Math.pow(x, (double)2))+(c*x)+d;
        return resultado;
    }
    public static void hacertabla(int intentos, double raiz1, double raiz2, double a, double b, double c, double d, DefaultTableModel modelo, JLabel info){
        int []n = new int[intentos];
        double [] xo = new double[intentos];
	double [] xi = new double[intentos];
	double [] x2 = new double[intentos];
        double [] fxo = new double[intentos];
	double [] fxi = new double[intentos];
	double [] fx2 = new double[intentos];
        double [] error = new double[intentos];
        double calculo1, calculo2, calculo3;
        for(int i=0; i<intentos; i++)
        {
            n[i]=(i+1);
            if(i==0)
            {
                xo[i]=raiz1;
                xi[i]=raiz2;
            }
            else
            {
                xo[i]=xi[i-1];
                xi[i]=x2[i-1];
            }
            
            fxo[i]=FuncionEntrante(a, b, c, d, xo[i]);
            fxi[i]=FuncionEntrante(a, b, c, d, xi[i]);
            calculo1=((double)xi[i]-(double)xo[i])*(double)fxi[i];
            calculo2=(double)fxi[i]-(double)fxo[i];
            calculo3=(double)calculo1/(double)calculo2;
            x2[i]=xi[i]-(double)calculo3;
            fx2[i]=FuncionEntrante(a, b, c, d, x2[i]);
            
            if(i==0)
            {
                error[i]=0;
            }
            else
            {
                error[i]=Math.abs(fx2[i]-fx2[i-1]);
            }
        }
        
        Object []yano = new Object[8];
        //Añadir condiccion para que salga de este formato solo caundo sean menores  E-3
        //Poner condiccion cuando se encuentre la raiz, solo me muestre los resultados hasta ahi
        
        //Para mayores de E-3
	//DecimalFormat dh = new DecimalFormat("##0.####");
	//Para menores de E-3
	//DecimalFormat df = new DecimalFormat("0.####E0");
        
        for(int i=0; i<intentos; i++)
        {
            yano[0]=n[i];
            yano[1]=CKambio(xo[i]);
            yano[2]=CKambio(xi[i]);
            yano[3]=CKambio(fxo[i]);
            yano[4]=CKambio(fxi[i]);
            yano[5]=CKambio(x2[i]);
            yano[6]=CKambio(fx2[i]);
            yano[7]=CKambio(error[i]);
            //Añadir fila
            modelo.addRow(yano);
            //Romper bucle
            //if(n1[i]!=1 && fXr1[i]==0)
            //if(n[i]!=1 && error[i]==0)
            if(n[i]!=1 && Math.abs(fx2[i])< 1E-7)
            {
                break;
            }
            else if(n[i]==intentos)
            {
                info.setText("No converge porque la funcion no es  menor a E-7");
                //JOptionPane.showMessageDialog(null, "No converge porque la funcion no es  menor a E-7", "NO CONVERGE", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    public static String CKambio(Double num){
        //Para mayores de E-3
	DecimalFormat dh = new DecimalFormat("##0.########");
	//Para menores de E-3
	DecimalFormat df = new DecimalFormat("0.###E0");
        
        String cambio="";
        if(num==0){
                cambio = Double.toString(num);
            }else if( (num > 10E-3) || (num < -10E-3) ){
                cambio=dh.format(num);
            }else{
                cambio=df.format(num);
            }
        return cambio;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFormula1;
    private javax.swing.JLabel txtInformacion;
    // End of variables declaration//GEN-END:variables
}
